auto: true
markdown: rdiscount
permalink: /:categories/:title
paginate: 10
rdiscount extensions: [smart]
name: Overworld Map
description: A celebration of video game cartography.
url: http://overworldmap.com
media: http://media.everythingdigital.org/overworld/
