auto: true
markdown: rdiscount
permalink: /:categories/:title
paginate: 10
rdiscount extensions: [smart]
name: Overworld Map
description: A celebration of video game cartography.
url: http://overworldmap.com
media: http://9aae47647590f40e8b87-e0b4588320e25eb32e12d7a83a5ac594.r64.cf1.rackcdn.com/overworld/
